### ISSUE TITLE
Check Initialisation of devices

### ISSUE THREAD

**Issue by jbinz** [catsystems/cats-embedded#143]
Currently, if a device fails the initialisation, the software is stuck in an infinite loop. Use error handling to handle this.

**Comment by l-jost** [comment]
Idea:

On each device initialization add a timeout and a boolean if it worked or not.
Check at the end of the initialization task each device and if it failed initialization.
Propagate that information to the sensor readout task. If initialization failed do not read out.
The global variable then stays at 0 and is being caught by the sensor elimination for the state estimation.
