### ISSUE TITLE
Recognize When UART Communication Fails

### ISSUE THREAD

**Issue by stojadin2701** [catsystems/cats-embedded#234]
It seems that the UART communication with the telemetry chip is broken on my board. The system becomes unresponsive after calling:

` HAL_UART_Receive_IT(&TELEMETRY_UART_HANDLE, (uint8_t*)&uart_char, 1);`
 
Situations like these should be recognized in advance and reported to the user.

**Comment by l-jost** [comment]
Fixed with pull request #241
