### ISSUE TITLE
Check Initialization of devices and have some error handling on them

### ISSUE THREAD

**Issue by jbinz** [catsystems/cats-embedded#91]
Idea:
1. On each device initialization add a timeout and a boolean if it worked or not.
2. Check at the end of the initialization task each device and if it failed initialization.
3. Propagate that information to the sensor readout task. If initialization failed do not read out.
4.  The global variable then stays at 0 and is being caught by the sensor elimination for the state estimation.

**Comment by l-jost** [comment]
duplicate
